socceraction/spadl/opta.py, socceraction/spadl/statsbomb.py, socceraction/spadl/wyscout.py
I was playing with the new dump of Wyscout data and when converting it into SPADL it fails dealing with substitutes. This is because the existing logic sets the `substitutions` variable to `True` or `False` because the assignment of the empty list is outside of the `.get("substitutions")` method call.
I also ran into a json.load problem which seems to be related to not using utf-8 encoding (issue #11 seems to be the same issue) so I've pushed a commit to fix that too.
=> Fix retrieval of Wyscout substitutions

socceraction/xthreat.py
Modifies the xT implementation to incorporate the probability of moving from (x,y) --> (z,w) successfully. This probability term is directly absorbed into the transition matrix.
The `s` term for the 'Move' branch described in the [slide](https://docs.google.com/presentation/d/1tu603CdONhI17AZTrd3mdf1UAf7k-rHwwCLSU_tCx6g/edit#slide=id.g6220bb1d1d_0_287) below is what's being added:
`T(x,y,z,w) = p(x,y,z,w) * s(x,y,z,w) = (count(x,y,z,w) / count(x,y,_,_)) * (count_successful(x,y,z,w) / count(x,y,z,w)) = count_successful(x,y,z,w) / count(x,y,_,_)`
xT map (`eps = 1e-5`) before change:
xT map (`eps = 1e-5`) after change:
=> [xT] Incorporates movement success probability

socceraction/atomic/vaep/features.py
When following the tutorials and creating the feature matrix in the tutorials, the goalscore function was also counting goalkick actions.
=> adjusting goalscore function to not match goalkick when looking for goals fix #44

socceraction/atomic/vaep/labels.py, tests/atomic/test_atomic_vaep.py
The label function "goal_from_shot" seemed to not have been correctly changed from socceraction.vaep.labels to socceraction.atomic.vaep.labels and misses all goals as there are no actions that have both a "shot" and "goal" actiontype.
This PR fixes this issue and adds a test to check correctness of the function,
=> fix atomic label function goal_from_shot

socceraction/data/opta/loader.py
The default glob patterns for the Opta XML and JSON feeds were not correct.
=> Fix default Opta feeds

socceraction/spadl/opta.py
Fixes #410
The SPADL converter only checked for the presence of qualifier 15 to determine the bodypart of actions. Therefore, it missed all headed passes. Now, it also looks for the following qualifiers:
- 3 (Head pass): Pass made with a players head
- 168 (Flick-on): Pass where a player has "flicked" the ball forward using their head
=> Fix Opta to SPADL conversion of headed passes

socceraction/spadl/opta.py, socceraction/spadl/statsbomb.py, socceraction/spadl/wyscout.py
Fixes #262 
Passes with the following outcomes are now converted to a "non_action" in SPADL:
- Injury clearance: ball is played out of bounds to stop play for an injury (all data providers)
- Unknown: outcome is unknown (i.e., foul was called while in mid-flight) (StatsBomb only)
=> Discard fairplay actions and interrupted events

.github/workflows/ci.yml
The Python version was retrieved from a non-existing variable matrix, resulting in an unpredictable Python version.
=> Fix python version in CI setup script

socceraction/xthreat.py
The `xthreat._safe_divide` function would sometimes return a integer array instead of floats, resulting in an all-zero xT grid.
=> Fix xT model fitting

socceraction/data/opta/parsers/ma3_json.py
The "game_day" field is not provided for all tournaments in Stats Perform feeds.
=> Allow missing "game_day" in MA3 feeds

socceraction/spadl/opta.py
- The "ball recovery" event was previously discarded in the conversion to SPADL. It is now used to mark the start of a new dribble.
- Opta inserts a "ball touch" event after passes that are deflected and sets the end location of the deflected pass to the location where it got deflected. As a consequence, a dribble event was added between the location where the ball was deflected and the start location of the next action in the SPADL version. This commit sets the end location of the deflected pass to the start location of the next action and the outcome to "success" if the deflected pass reached a teammate.
Fixes #519
=> Fix SPADL conversion of Opta ball touches and recoveries

socceraction/vaep/features.py, tests/vaep/test_features.py
The categorical 'actiontype', 'result', 'bodypart' and 'bodypart_detailed' features now have dtype "pd.Categorical". This allows machine learning frameworks such as xgboost to automatically recognize these features as being categorical and handle them accordingly.
The features are now strings (e.g., "pass") instead of integer ids. Also, the column name for each of these features was renamed as follows: type_id -> actiontype
result_id -> result
bodypart_id -> bodypart
=> Use categorical dtype for categorical features

socceraction/data/statsbomb/loader.py, socceraction/data/statsbomb/schema.py, socceraction/spadl/statsbomb.py, tests/spadl/test_statsbomb.py
The SPADL "time_seconds" field is now derived from the StatsBomb "timestamp" field instead of the "minute" and "second" field. This allows timestamps with sub-second accuracy in the SPADL format.
=> High fidelity StatsBomb timestamps

socceraction/spadl/statsbomb.py
The y-coordinate of a shot in the goal frame is always detailed to a tenth of a yard.
=> [StatsBomb] Fix fidelity of shot y-coordinates

socceraction/spadl/statsbomb.py
According to the specification of SPADL, the result of a foul should always be "fail" or a card.
=> [StatsBomb] The default result of a foul should always be 'fail'

socceraction/data/opta/parsers/f24_json.py, socceraction/data/opta/parsers/f24_xml.py, socceraction/data/opta/parsers/ma3_json.py, socceraction/data/opta/parsers/whoscored.py
When an event had start- or end-coordinates equal to zero, these were incorrectly handled as missing coordinates.
=> [Opta] Fix bug when x or y-coordinate is zero

socceraction/spadl/wyscout.py
The end coordinates of shots are estimated from tags that indicate where the ball would end up in goal. These tags are also recorded for save attempts and blocked shots. However, the end coordinate should only be modified for non-blocked shots. The end-coordinates of blocked shots should be the location of the block.
=> [Wyscout] Only estimate goalmouth coordinates for shots

socceraction/spadl/opta.py
A "freekick_crossed" in SPADL is a long freekick. It includes, but is not limited to, a freekick that is played in from wide areas into the box.
=> [Opta] Fix definition of 'freekick_crossed'

socceraction/spadl/wyscout.py
Cards were not considered in the "result" field of fouls when converting from Wyscout to SPADL.
=> [Wyscout] Add cards to result of fouls

socceraction/spadl/wyscout.py
"Missed ball" is a type of Touch when the player is trying to control the ball, but can’t reach it. These touches should not be converted to a pass or dribble since the acting player does not touch the ball.
=> [Wyscout] Ignore "missed ball"-touches

socceraction/data/opta/loader.py, socceraction/spadl/opta.py, socceraction/spadl/statsbomb.py, socceraction/spadl/wyscout.py
When two events or actions have identical timestamps, we should keep the order in the original data. However, since the default sorting algorithm used by Panda's sort_values-method is not stable, the order of such events or actions could get switched.
=> Use stable sort for ordering events/actions

socceraction/spadl/wyscout.py, tests/spadl/test_wyscout.py
When a clearance or acceleration was tagged as an interception, no interception action was inserted before the clearance or acceleration.
=> [Wyscout] Insert interceptions before clearances and accelerations

socceraction/spadl/base.py
This makes sure that no dribbles are added at the end location of actions that are followed by a foul of the receiving player (or a teammate).
Closes #594
=> [SPADL] Do not insert synthetic dribbles before offensive fouls

socceraction/vaep/features.py
The 'result' feature generator returned null values for all inputs.
Fixes #662
=> Fix 'result' feature generator

socceraction/data/opta/loader.py
This commit improves the performance of the OptaLoader.competitions() method. Previously, this method was very slow when loading data from a directory with many data files, since it parsed every single file. This is solved by parsing only one file per competition-season pair.
=> [Opta] Load competitions dataframe more efficiently

socceraction/spadl/kloppy.py
Fixes a typo in the SPADL result name: "own_goal" --> "owngoal"
=> [Kloppy] Fix parsing own goals

socceraction/spadl/opta.py, tests/spadl/test_opta.py
The _fix_unintentional_ball_touches method was added to deal with "unintentional ball touch" events (`type_id=61 + outcome=0`). These are typically deflections. It sets the result of an action to "success" if the team manages to keep possession.
But this should only be applied to passes (i.e., actions for which the result depends on keeping possession). For example, the result of a shot should depend on whether a goal was scored.
Fixes #725
=> [Opta] Apply _fix_unintentional_ball_touches only to passes

socceraction/data/opta/loader.py, tests/data/test_load_opta.py
Adds support for loading Opta data from a file path that contains accented characters.
Fixes #730
=> [Opta] Support feeds with accented characters

socceraction/vaep/base.py
Recent versions of xgboost have moved some arguments from the fit method to the constructor.
=> Update xgboost arguments

socceraction/vaep/features.py, tests/vaep/test_features.py
The "time_seconds_overall" feature that is generated by the "time" function now handles extra time correctly.
Fixes #670
=> [VAEP] Support extra time in "time" feature

socceraction/atomic/vaep/labels.py, tests/atomic/test_atomic_labels.py
This commit fixes a bug in the scores and concedes functions in atomic vaep, where the intention is to grab the last element in the dataframe and assign that value to the end of the shifted dataframe.
See also #718
Fixes #749
=> [Atomic-VAEP] use iloc to select last value in the dataframe

.github/workflows/ci.yml
From September 2nd, 2024, the GitHub action update-artifact does not upload hidden files and folders by default. This caused trouble with .coverage files.
=> Fix missing coverage upload

socceraction/spadl/opta.py
close #850 
I could not get the tests to work locally, partly because I am running on MacOs:
For instance in:
```python
def test_universal_feeds(tmpdir: local) -> None:
"""It should replace forward slashes in glob patterns on Windows."""
feeds = {
"myfeed": "{competition_id}/{season_id}/{game_id}.json",
}
parser = {
"myfeed": opta.parsers.base.OptaParser,
}
loader = opta.OptaLoader(root=str(tmpdir), parser=parser, feeds=feeds)
if "win" in sys.platform:
assert loader.feeds["myfeed"] == "{competition_id}\\{season_id}\\{game_id}.json"
elif "linux" in sys.platform:
assert loader.feeds["myfeed"] == "{competition_id}/{season_id}/{game_id}.json"
```
`sys.platform` returns `"darwin"` for MacOs, which results in the test assuming that this is a Windows based system and thus this test fails locally …
=> Differentiate between keeper and fieldplayer save event in opta-spadl.
