socceraction/spadl/statsbomb.py
- During the conversion from StatsBomb json format to HDF, a list of all players is constructed by iterating over all games and appending the players that appeared in that game to a list. However, because duplicate players were only removed after the loop, this code results in an OutOfMemory error when converting a large dataset.
- Opening and closing HDF files is very slow. Using a context manager instead of
`pd.read_hdf` and `pd.DataFrame.to_hdf` improves the speed by a factor ~5.
=> Improve speed and memory usage of StatsBomb converter

public-notebooks/1-download-statsbomb-data.ipynb
This commit adds a cell to the notebook that checks whether the folder `../data` exists and - if not - creates this folder.
=> Make sure data folder exists

socceraction/xthreat.py
Adds an option to use bilinear interpolation when inferring the xT values at (x,y) locations. The raw xT grid is used to carry out this interpolation.
**Raw xT grid**
**Inferred xT values with interpolation** (note: the y-axis is reversed with respect to the original map, as is done during inference):
=> [xT] Bilinear interpolation for inference

docs/documentation/SPADL.rst
Changed 'baody' to 'body' on line number 90
=> Fix a small typo

socceraction/spadl/opta.py
Hi!
Now it's possible to pass tutorials with Perform's MA3 feeds.
=> MA3: improved extract functions

socceraction/atomic/spadl/base.py
Fixes Issue https://github.com/ML-KULeuven/socceraction/issues/199#issue-1145028706
=> Fixes bug in conversion of goals to atomic SPADL 

socceraction/data/opta/loader.py
Fixed seconds and timestamp parsers.
Tested on 6k matches from MA3. Now all of them parsed without errors.
=> Perform parser: bad data workarounds

socceraction/spadl/wyscout.py, tests/spadl/test_wyscout.py
Transform Simulations to failed take-on and remove all other off the ball fouls. Fixes Issue #240.
=> Remove off the ball fouls

README.md
fix: unnecessary full stop has been removed from the title.
Smile - this commit was recorded on a Zoom stream of https://www.meetup.com/twosseng/ with an absolutely amazing Kayode Emmanuel.
=> fix: unnecessary full stop has been removed

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, docs/documentation/install.rst, noxfile.py, poetry.lock, pyproject.toml, setup.cfg, socceraction/spadl/statsbomb.py, socceraction/spadl/wyscout.py, socceraction/xthreat.py, tests/datasets/download.py
Fixes #421
- Adds support for Python 3.11
- Drops support for Python 3.7
=> Support Python 3.11

socceraction/data/wyscout/loader.py
In the public Wyscout dataset, all events of a season are stored in a single large JSON file. As parsing this file is very expensive, commit b5adcb1 implemented caching. However, the cache was only used in the "events" method. This commit adds caching to the "players" method too, which uses the events to compute the "minutes played" field.
=> Improve performance PublicWyscoutLoader

socceraction/spadl/opta.py
Hi,
I tried running this but it didn't work because the boolean check on the list was performed with "is" rather than "==". I've made the change. Thank you once again for your help here!
Best,
- Karan
=> Removal of "is" for boolean check in "_fix_unintentional_ball_touches"

socceraction/spadl/statsbomb.py, tests/spadl/test_statsbomb.py
=> Support StatsBomb high fidelity coordinates

tests/spadl/test_statsbomb.py
StatsBomb updated the IDs of some events, resulting in broken test cases.
=> Update StatsBomb IDs in tests

socceraction/spadl/statsbomb.py
One touch passes off an interception are now split in two events (an interception + pass) in the SPADL representation.
=> Split StatsBomb interception passes in two events

socceraction/spadl/opta.py
Changes the body part of throw-ins from "foot" to "other".
=> [Opta] Set the body part of throw-ins to "other"

socceraction/spadl/opta.py
Opta set the result of an interception always to "success". According to the specification of SPADL, an interception must regain possession to be successful.
=> [Opta] Interceptions must regain possession to be successful

socceraction/spadl/opta.py
Changes the body part of 'save', 'claim', 'punch' and 'keeper pick-up' actions from "foot" to "other".
=> [Opta] Set body part of keeper actions to "other"

socceraction/spadl/base.py
This makes sure that no dribbles are inserted before headed shots.
Closes #613
=> [SPADL] Do not insert synthetic dribbles before headed shots

socceraction/atomic/spadl/utils.py, socceraction/spadl/utils.py, socceraction/vaep/features.py
=> Improve docs of "play_left_to_right"

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, docs/documentation/install.rst, noxfile.py, poetry.lock, pyproject.toml
=> Support Python 3.12
